/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertComponent: typeof import('./src/components/alert/AlertComponent.vue')['default']
    ButtonComponent: typeof import('./src/components/button/ButtonComponent.vue')['default']
    CardComponent: typeof import('./src/components/card/CardComponent.vue')['default']
    CheckboxComponent: typeof import('./src/components/checkbox/CheckboxComponent.vue')['default']
    DateTimeComponent: typeof import('./src/components/date-time/DateTimeComponent.vue')['default']
    InputComponent: typeof import('./src/components/input/InputComponent.vue')['default']
    LoadingComponent: typeof import('./src/components/loading/LoadingComponent.vue')['default']
    ModalComponent: typeof import('./src/components/modal/ModalComponent.vue')['default']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectComponent: typeof import('./src/components/select/SelectComponent.vue')['default']
    TitleComponent: typeof import('./src/components/title/TitleComponent.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULinkBase: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
  }
}
